# Generated by Django 4.1.1 on 2022-12-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_notes_file_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='notes',
            field=models.ManyToManyField(to='home.notes'),
        ),
    ]
