# Generated by Django 4.1.1 on 2023-02-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
