# Generated by Django 4.1.1 on 2023-02-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_notes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='file_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='name',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
