# Generated by Django 4.1.1 on 2023-03-02 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_audio_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supporting_Doc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, null=True)),
                ('supporting_doc', models.FileField(blank=True, null=True, upload_to='suporting_files/')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.notes')),
            ],
        ),
    ]
