# Generated by Django 4.1.1 on 2023-05-09 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_supporting_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='file_audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.audio'),
        ),
    ]
