# Generated by Django 4.1.1 on 2023-05-09 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_notes_file_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.audio'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notes',
            name='file_audio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='file_text',
            field=models.TextField(blank=True, max_length=45, null=True),
        ),
    ]
